# -*- coding: utf-8 -*-
"""Topsis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OWS9ydMF9yVtKJ-Tq7Izd33qmbvmZv76
"""

import pandas as pd
import numpy as np


def topsis(input_file, weights, impacts, output_file):
    data = pd.read_csv(input_file)

    data.iloc[:, 1:] = data.iloc[:, 1:].astype(float)

    w = np.array([float(x) for x in weights.split(",")])
    imp = impacts.split(",")

    values = data.iloc[:, 1:].to_numpy()

    denom = np.sqrt((values ** 2).sum(axis=0))
    norm_matrix = values / denom
    weighted_matrix = norm_matrix * w

    best = []
    worst = []

    for idx, sign in enumerate(imp):
        if sign == "+":
            best.append(weighted_matrix[:, idx].max())
            worst.append(weighted_matrix[:, idx].min())
        else:
            best.append(weighted_matrix[:, idx].min())
            worst.append(weighted_matrix[:, idx].max())

    best = np.array(best)
    worst = np.array(worst)

    dist_best = np.sqrt(((weighted_matrix - best) ** 2).sum(axis=1))
    dist_worst = np.sqrt(((weighted_matrix - worst) ** 2).sum(axis=1))

    score = dist_worst / (dist_best + dist_worst)

    data["Topsis Score"] = score
    data["Rank"] = data["Topsis Score"].rank(ascending=False, method="first").astype(int)

    data.to_csv(output_file, index=False)